# 高性能路由配置示例

[server]
host = "127.0.0.1"
port = 1080
max_connections = 1000

[high_performance_router]
default_outbound = "direct"

# 路由规则
[[high_performance_router.rules]]
rule_sets = ["google_domains", "google_ips"]
outbound = "proxy"

[[high_performance_router.rules]]
rule_sets = ["blocked_domains"]
outbound = "blackhole"

[[high_performance_router.rules]]
rule_sets = ["private_ips"]
outbound = "direct"

# 缓存配置
[high_performance_router.cache]
max_size = 50000
enabled = true

# 规则集合文件
[high_performance_router.rule_set_files]
domain_files = ["rules/domains.json", "rules/blocked.json"]
ip_files = ["rules/ips.json", "rules/private.json"]

# 出站配置
[[outbounds]]
name = "direct"
type = "direct"

[[outbounds]]
name = "proxy"
type = "socks5"
address = "127.0.0.1:9050"

[[outbounds]]
name = "blackhole"
type = "blackhole"
