pub mod error;
pub mod protocol;
pub mod proxy;
pub mod zero_copy;
pub mod dns;
pub mod connection_pool;
pub mod config;
pub mod traffic_mark;
pub mod outbound;
pub mod router;
pub mod inbound;
pub mod protocols;

pub use error::{ProxyError, Result};
pub use protocol::{Address, Socks5Request, Socks5Response};
pub use proxy::Socks5Proxy;
pub use zero_copy::{ZeroCopyRelay, ZeroCopyBuffer, OptimizedCopier};
pub use outbound::{OutboundConnector, OutboundManager};
pub use router::{Router, RouteDecision};
pub use protocols::{Protocol, DirectProtocol, Socks5Protocol, VlessProtocol, BlackholeProtocol, TproxyProtocol};
pub use inbound::{Inbound, ProtocolInbound};
